'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TRUONGANHQUAN_2210900058_LESSION9Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TRUONGANHQUAN_2210900058_LESSION9Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property TaqKhoa() As DbSet(Of TaqKhoa)
    Public Overridable Property TaqSinhvien() As DbSet(Of TaqSinhvien)

End Class
