'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TaqSinhvien
    Public Property TaqMaSV As String
    Public Property TaqHoSV As String
    Public Property TaqTenSV As String
    Public Property TaqNgaySinh As Nullable(Of Date)
    Public Property TaqPhai As Nullable(Of Boolean)
    Public Property TaqPhone As String
    Public Property TaqEmail As String
    Public Property TaqMakhoa As String

    Public Overridable Property TaqKhoa As TaqKhoa

End Class
